name: Remove Subgraph

on: [ pull_request_review, workflow_dispatch ]

jobs:
  Remove:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup Latest Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: 4.0.1

      - name: remove subgraph
        env:
          TESTNET_GRAPH_NODE_URL: ${{ secrets.TESTNET_GRAPH_NODE_URL }}
          TESTNET_GRAPH_IPFS_URL: ${{ secrets.TESTNET_GRAPH_IPFS_URL }}
        run: |
          chmod +x ./scripts/remove-fxcore.sh
          ./scripts/remove-fxcore.sh
